codecov:
  ci:
    - "travis.org"
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2
    wait_for_ci: yes
coverage:
  precision: 3
  round: nearest
  range: "10...100"
  status:
    project:
      default: yes
      target: auto
      threshold: null
      base: pr
      flags: null
      if_ci_failed: error