name: First Issue Greeting

on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Issue Greeting
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'This looks like your first contribution. Thank you, and welcome to the community!'
